# Generated by Django 3.1.13 on 2021-11-24 15:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdl_rest_api', '0002_auto_20211123_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experimentbase',
            name='maxRuntime',
            field=models.PositiveIntegerField(blank=True, default=5, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(120)]),
        ),
    ]
