# Generated by Django 3.1.13 on 2021-11-30 13:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cdl_rest_api', '0003_auto_20211124_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment',
            name='experimentId',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='experimentbase_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='cdl_rest_api.experimentbase'),
        ),
    ]
