# Generated by Django 3.1.13 on 2021-12-21 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cdl_rest_api', '0004_coincidences_countrates_experimentdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='experimentresult',
            name='experimentData',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cdl_rest_api.experimentdata'),
        ),
    ]
