# Generated by Django 3.1.13 on 2021-12-06 10:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdl_rest_api', '0005_auto_20211130_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='experimentbase',
            name='circuitID',
            field=models.PositiveIntegerField(default=4, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(22)]),
            preserve_default=False,
        ),
    ]
