# Generated by Django 3.1.13 on 2022-03-17 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cdl_rest_api', '0005_experimentresult_experimentdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experimentdata',
            name='encodedQubitMeasurements',
        ),
        migrations.DeleteModel(
            name='Coincidences',
        ),
    ]
