# Generated by Django 3.1.13 on 2022-03-17 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdl_rest_api', '0006_auto_20220317_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='experimentdata',
            name='coincidenceCounts',
            field=models.JSONField(default='default'),
        ),
    ]
