# Generated by Django 3.1.13 on 2021-12-06 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cdl_rest_api', '0006_experimentbase_circuitid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experimentbase',
            old_name='circuitID',
            new_name='circuitId',
        ),
    ]
