# Generated by Django 3.1.13 on 2022-03-17 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdl_rest_api', '0007_experimentdata_coincidencecounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experimentdata',
            name='coincidenceCounts',
            field=models.JSONField(default=dict),
        ),
    ]
