# Generated by Django 3.1.13 on 2022-03-21 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cdl_rest_api', '0008_auto_20220317_1408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qubitcomputing',
            name='circuitConfiguration',
        ),
    ]
