# Generated by Django 3.1.13 on 2022-09-01 15:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdl_rest_api', '0009_remove_qubitcomputing_circuitconfiguration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experimentbase',
            name='circuitId',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(23)]),
        ),
    ]
