# Generated by Django 3.1.13 on 2022-09-06 05:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cdl_rest_api', '0010_auto_20220901_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experiment',
            name='user',
        ),
        migrations.AddField(
            model_name='experiment',
            name='user_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
